"""Generate RFC 3454 table A.1 using Python's fixed Unicode 3.2 database.

Run from this directory with: python3 gen_saslprep_unassigned.py
Only the Python standard library is needed; no network access is required.
"""

from pathlib import Path
import stringprep
from unicodedata import ucd_3_2_0

assert ucd_3_2_0.unidata_version == "3.2.0"


def ranges(start, stop):
    first = None
    for code in range(start, stop):
        if stringprep.in_table_a1(chr(code)):
            if first is None:
                first = code
        elif first is not None:
            yield first, code - 1
            first = None
    if first is not None:
        yield first, stop - 1


lines = [
    "// Code generated by gen_saslprep_unassigned.py; DO NOT EDIT.",
    "",
    "package pgconn",
    "",
    'import "unicode"',
    "",
    "//go:generate python3 gen_saslprep_unassigned.py",
    "",
    "// saslprepUnassigned is RFC 3454 table A.1: code points unassigned in",
    "// Unicode 3.2. This table must not track the Go toolchain's Unicode version.",
    "// https://www.rfc-editor.org/rfc/rfc3454#appendix-A.1",
    "var saslprepUnassigned = &unicode.RangeTable{",
]
for name, width, start, stop in [
    ("R16", 16, 0, 0x10000),
    ("R32", 32, 0x10000, 0x110000),
]:
    lines.append(f"\t{name}: []unicode.Range{width}{{")
    for first, last in ranges(start, stop):
        lines.append(f"\t\t{{0x{first:04x}, 0x{last:04x}, 1}},")
    lines.append("\t},")
lines.extend(["}", ""])
Path(__file__).with_name("saslprep_unassigned.go").write_text(
    "\n".join(lines), encoding="utf-8"
)
